# Generated by Django 4.0.3 on 2022-04-20 08:06

from django.db import migrations


def insert_default_user(apps, schema_editor):
    User = apps.get_model('messagebot', 'User')
    for user_type in ('自己', '父母', '丈夫', '妻子', '孩子', '其他'):
        user = User(name=user_type)
        user.save()


def insert_default_type(apps, schema_editor):
    Type = apps.get_model('messagebot', 'Type')
    for record_type in ('早餐', '午餐', '晚餐', '居家', '水電', '網路', '電話', '醫療', '日常用品', '其他'):
        type_record = Type(name=record_type)
        type_record.save()


class Migration(migrations.Migration):

    dependencies = [
        ('messagebot', '0001_initial'),
    ]


    operations = [
        migrations.RunPython(insert_default_user),
        migrations.RunPython(insert_default_type),
    ]
