# Generated by Django 4.0.3 on 2022-04-22 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messagebot', '0004_rename_accountinguser_accountingmember_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accountingrecord',
            old_name='type_id',
            new_name='accounting_type_id',
        ),
        migrations.RenameField(
            model_name='accountingrecord',
            old_name='user_id',
            new_name='member_id',
        ),
    ]
